# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dev\Projects-python\Qt5BrowserBuild\winvenv\Lib\site-packages\PySide2\examples\charts\chartthemes\themewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThemeWidgetForm(object):
    def setupUi(self, ThemeWidgetForm):
        ThemeWidgetForm.setObjectName("ThemeWidgetForm")
        ThemeWidgetForm.resize(900, 600)
        self.gridLayout = QtWidgets.QGridLayout(ThemeWidgetForm)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.themeLabel = QtWidgets.QLabel(ThemeWidgetForm)
        self.themeLabel.setObjectName("themeLabel")
        self.horizontalLayout.addWidget(self.themeLabel)
        self.themeComboBox = QtWidgets.QComboBox(ThemeWidgetForm)
        self.themeComboBox.setObjectName("themeComboBox")
        self.horizontalLayout.addWidget(self.themeComboBox)
        self.animatedLabel = QtWidgets.QLabel(ThemeWidgetForm)
        self.animatedLabel.setObjectName("animatedLabel")
        self.horizontalLayout.addWidget(self.animatedLabel)
        self.animatedComboBox = QtWidgets.QComboBox(ThemeWidgetForm)
        self.animatedComboBox.setObjectName("animatedComboBox")
        self.horizontalLayout.addWidget(self.animatedComboBox)
        self.legendLabel = QtWidgets.QLabel(ThemeWidgetForm)
        self.legendLabel.setObjectName("legendLabel")
        self.horizontalLayout.addWidget(self.legendLabel)
        self.legendComboBox = QtWidgets.QComboBox(ThemeWidgetForm)
        self.legendComboBox.setObjectName("legendComboBox")
        self.horizontalLayout.addWidget(self.legendComboBox)
        self.antialiasCheckBox = QtWidgets.QCheckBox(ThemeWidgetForm)
        self.antialiasCheckBox.setChecked(False)
        self.antialiasCheckBox.setObjectName("antialiasCheckBox")
        self.horizontalLayout.addWidget(self.antialiasCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)

        self.retranslateUi(ThemeWidgetForm)
        self.themeComboBox.currentIndexChanged['int'].connect(ThemeWidgetForm.updateUI)
        self.antialiasCheckBox.toggled['bool'].connect(ThemeWidgetForm.updateUI)
        self.legendComboBox.currentIndexChanged['int'].connect(ThemeWidgetForm.updateUI)
        self.animatedComboBox.currentIndexChanged['int'].connect(ThemeWidgetForm.updateUI)
        QtCore.QMetaObject.connectSlotsByName(ThemeWidgetForm)

    def retranslateUi(self, ThemeWidgetForm):
        _translate = QtCore.QCoreApplication.translate
        self.themeLabel.setText(_translate("ThemeWidgetForm", "Theme:"))
        self.animatedLabel.setText(_translate("ThemeWidgetForm", "Animation:"))
        self.legendLabel.setText(_translate("ThemeWidgetForm", "Legend:"))
        self.antialiasCheckBox.setText(_translate("ThemeWidgetForm", "Anti-aliasing"))
